config/routes.rb
Rails.application.routes.draw do

  #ログイン
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #トップページ
  root to: 'toppages#index'
  
  #アカウント作成・編集・削除
  get 'signup', to: 'users#new'
  resources :users do
    collection do
      get :search
    end
  end
  
  #Book作成
  resources :books

  
  #WholeAnswer作成
  resources :whole_answers
  
  #base_periods作成
  resources :base_periods, :except => [:new] do
    collection do
      get :new_names
      get :new_contents
      post :create_names
      post :create_contents
    end
    member do
      get :new_content
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  #パスワードセキュリティ
  has_secure_password

  #Modelの関係づけ
  has_many :books
  has_many :relationships
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'

  #has_many_throughの形（textコピペ）
  has_many :followings, through: :relationships, source: :follow
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  #バリデーション
  validates :name, presence: true, length: { maximum:50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

                    
  #フォロー機能（textコピペ）
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  #def friends_booksをあとで作成
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all.page(params[:page])
  end

  def search
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'アカウントは正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'アカウントは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:success] = 'アカウントは正常に削除されました'
    redirect_to user_url
  end
  
  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :birth_date, :password, :password_confirmation)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<div class="container contents-wrapper"> 
  <% if users.any? %>
    <ul class="media-list">
      <% users.each do |user| %>
        <li class="media">
          <div class="media-left">
            <!-- あとで画像いれる -->
          </div>
          <div class="media-body">
            <div>
              <%= user.name %>
            </div>
            <div>
              <p><%= link_to 'View profile', user_path(user) %></p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <%= paginate users %>
  <% end %>
</div>

app/views/users/edit.html.erb
<!-- users#edit --> 
  
<div class="container contents-wrapper">
  <div class="text-center">
    <h1>id: <%= @user.id %> のアカウント編集ページ</h1>
  </div>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
  
      <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
  
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :email, 'Email' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :birth_date, '生年月日' %>
          <%= f.text_field :birth_date, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password_confirmation, 'Confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
  
        <%= f.submit 'アカウント情報を更新', class: 'btn btn-primary btn-block' %>
      <% end %>
      
      <%= link_to 'マイページに戻る', user_path %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!-- users#index -->

<div class="container contents-wrapper">
  <%= render 'users', users: @users %>
</div>

app/views/users/new.html.erb
<!-- users#new -->

<div class="container contents-wrapper">
  <div class="text-center">
    <h1>アカウント作成</h1>
  </div>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
  
      <%= form_for(@user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
  
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :email, 'Email' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :birth_date, '生年月日' %>
          <%= f.text_field :birth_date, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password, 'Password' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password_confirmation, 'Confirmation' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
  
        <%= f.submit 'アカウント作成', class: 'btn btn-primary btn-block' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- users#show -->

<div class="container contents-wrapper">
  <div class="row">
    <aside class="col-xs-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @user.name %></h3>
        </div>
        <div class="panel-body">
          <!-- あとで画像いれる <img class="media-object img-rounded img-responsive" src="" alt="">--> 
        <%= link_to 'アカウント情報を編集する', edit_user_path(@user) %><br>
        <%= link_to '新規Bookの投稿', new_book_path, class: 'btn btn-info' %>
        </div>
      </div>
    </aside>
    <div class="col-xs-8">
      <ul class="nav nav-tabs nav-justified">
        <li><a href="#">My Books</a></li>
        <li><a href="#">友達</a></li>
      </ul>
    </div>
  </div>
</div>