config/routes.rb
Rails.application.routes.draw do

  #ログイン
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #トップページ
  root to: 'toppages#index'
  
  #アカウント作成・編集・削除
  get 'signup', to: 'users#new'
  resources :users do
    collection do
      get :search
    end
  end
  
  #Book作成
  resources :books

  
  #WholeAnswer作成
  resources :whole_answers
  
  #base_periods作成
  resources :base_periods, :except => [:new] do
    collection do
      get :new_names
      get :new_contents
      post :create_names
      post :create_contents
    end
    member do
      get :new_content
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  #トップページに自分のbook_photoを表示してbook#showへのリンク設置
  def index
    if logged_in?
      @book = current_user.books.build  # form_for 用

    end
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/index.html.erb
<!-- toppage#index -->

	<% if logged_in? %>
	
	<!-- ログイン完了後トップページ -->
	<div class="container contents-wrapper">
	  <p>ログイン完了ユーザ: <%= current_user.name %></p>
	
	
	  <%= link_to '新規Bookの投稿', new_book_path %>
	</div>
	
	
	<% else %>
	<!-- ログイン前トップページ -->  
	
		<!-- Header -->
		<header id="head">
			<div class="container">
				<div class="row">
					<h1 class="lead">もっと、人を、好きになる。</h1>
					<p class="tagline"></p>
					<div class="btn btn-original" role="button"><%= link_to 'アカウント登録', signup_path %></div>
					<div class="btn btn-original" role="button"><%= link_to 'ログイン', login_path %></div>
				</div>
			</div>
		</header>
		<!-- /Header -->
	
		<!-- Intro -->
		<div class="container text-center">
			<br> <br>
			<h2 class="thin">人となりを、知れば知るほど、好きになる。</h2>
			<p class="text-muted">
				人となりBookは、数問の質問に答えるだけで、人となりがわかるストーリーが作成でき、<br>
      			友人や仕事仲間とシェアすることができるサービスです。</p>
			</p>
		</div>
		<!-- /Intro-->
			
		<!-- Highlights - jumbotron -->
		<div class="jumbotron top-space">
			<div class="container">
				
				<h3 class="text-center thin">人となりBookの使い方</h3>
				
				<div class="row">
					<div class="col-md-3 col-sm-6 highlight">
						<div class="h-caption"><h4><i class="fa fa-heart fa-5"></i>友達同士で</h4></div>
						<div class="h-body text-center">
							<p>仲良しでも、昔のことは意外と知らないもの。大切な友達との仲をさらに深めるましょう。知れば知るほど、もっと好きになります。 </p>
						</div>
					</div>
					<div class="col-md-3 col-sm-6 highlight">
						<div class="h-caption"><h4><i class="fa fa-building fa-5"></i>仕事仲間で</h4></div>
						<div class="h-body text-center">
							<p>良いチームになるには、深い相互理解が不可欠です。仲間のこだわりどころ・大切にしたいこと、把握できていますか？</p>
						</div>
					</div>
					<div class="col-md-3 col-sm-6 highlight">
						<div class="h-caption"><h4><i class="fa fa-smile-o fa-5"></i>初めましてに</h4></div>
						<div class="h-body text-center">
							<p>ネット上での出会いもとても多くなりました。でも、価値観の合わない人とのデートにお金や時間を浪費していませんか？ </p>
						</div>
					</div>
					<div class="col-md-3 col-sm-6 highlight">
						<div class="h-caption"><h4><i class="fa fa-cogs fa-5"></i>自己分析に</h4></div>
						<div class="h-body text-center">
							<p>就活で必須の自己分析。でも、タイプを分類しても天職は見つかりません。自分の価値観・想いを整理することが第一歩です。</p>
						</div>
					</div>
				</div> <!-- /row  -->
			
			</div>
		</div>
		<!-- /Highlights -->
	
		<!-- container -->
		<div class="container">
	
			<h2 class="text-center top-space">人となりBookをはじめよう</h2>
			<br>
	
			<div class="row text-center">
				<div class="col-md-2"></div>
				<div class="col-md-3 highlight btn btn-original center-block" role="button"><%= link_to 'アカウント登録', signup_path %></div>
				<div class="col-md-2"></div>
				<div class="col-md-3 highlight btn btn-original center-block" role="button"><%= link_to 'ログイン', login_path %></div>
				<div class="col-md-2"></div>
			</div> <!-- /row -->

	
			<div class="jumbotron top-space">
				<p>サンプルBookを表示</p>
	  		</div>
	
		</div>	<!-- /container -->
		
		<!-- Social links. @TODO: replace by link/instructions in template -->
		<section id="social">
			<div class="container">
				<div class="wrapper clearfix">
					<!-- AddThis Button BEGIN -->
					<div class="addthis_toolbox addthis_default_style">
					<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
					<a class="addthis_button_tweet"></a>
					<a class="addthis_button_linkedin_counter"></a>
					<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
					</div>
					<!-- AddThis Button END -->
				</div>
			</div>
		</section>
		<!-- /social links -->
	<% end %>