config/routes.rb
Rails.application.routes.draw do

  #ログイン
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #トップページ
  root to: 'toppages#index'
  
  #アカウント作成・編集・削除
  get 'signup', to: 'users#new'
  resources :users do
    collection do
      get :search
    end
  end
  
  #Book作成
  resources :books

  
  #WholeAnswer作成
  resources :whole_answers
  
  #base_periods作成
  resources :base_periods, :except => [:new] do
    collection do
      get :new_names
      get :new_contents
      post :create_names
      post :create_contents
    end
    member do
      get :new_content
    end
  end
end

app/models/base_period.rb
class BasePeriod < ApplicationRecord
  
  #Modelの関係づけ
  belongs_to :book
  has_many :periods
  has_many :whole_answers, through: :periods
  
  #has_many_throughの形（必要なら作成する）
  
  #バリデーション
  validates :name, presence: true, length:{ maximum:100 }
  
end

app/controllers/base_periods_controller.rb
class BasePeriodsController < ApplicationController
  before_action :require_user_logged_in
  
  def index
     @base_periods = BasePeriod.all
  end

  def show
    @base_period = BasePeriod.find(params[:id])
  end

  
  def new_names
    @book = Book.find(params[:book_id])
    @base_periods = 7.times.each do |count|
      @book.base_periods.build
    end
    @base_period = @book.base_periods.build
  end
  
  def new_contents
    @base_periods = BasePeriod.where(id: params[:base_period_id])
    @book = Book.find(params[:book_id])
  end

  def new_content
    @base_periods = BasePeriod.find_by(id: params[:id])
    render :new_contents
  end


  def create # これ使ってない気がする
    @book = Book.find(params[:book_id])
    @base_periods = @book.base_periods.build(base_periods_params)
    
    if @base_periods.save
      flash[:success] = 'period.nameを保存しました。'
      redirect_to new_contents_base_periods_path(@base_periods)
    else
      @base_periods= @book.base_periods.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'period.nameの保存に失敗しました。'
      render 'toppages/index'
    end
  end


  def edit
    @base_period = BasePeriod.find(params[:id])
  end

  def update
    @base_period = BasePeriod.find(params[:id])

    if @base_period.update(base_period_params)
      flash[:success] = 'period は正常に更新されました'
      redirect_to new_whole_answer_path(book_id: @base_period.book_id)
    else
      flash.now[:danger] = 'period は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @base_period = BasePeriod.find(params[:id])
    @base_period.destroy
    flash[:success] = 'periodを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private

  def base_period_params　#使っていない気がする
    params.require(:base_period).permit(:name, :content)
  end
  
  def base_periods_params　#使っていない気がする
    params.require(:book).permit(base_periods_attributes: [:name, :content])
  end
  
  
end

app/helpers/base_periods_helper.rb
module BasePeriodsHelper
end

app/views/base_periods/new_contents.html.erb
<!-- base_periods#new_contents -->

<div class="container contents-wrapper">
  <h2>それぞれどんな時期だったか、印象的な出来事などをまとめてみよう</h2>
  
<!-- ユーザーが入力したbase_period.nameの数だけ繰り返し入力する-->

  <!-- base_periodsのcontentの登録(books#updateに回す)-->   
  <%= form_for(@book, url: book_path(@book , xxx: "zzz"), html: {method: "patch"}) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    
    <% @base_periods.each do |base_period| %>
      <%= f.fields_for :base_periods, base_period do |bp| %>
        <%= bp.label :content, base_period.name %>
        <%= bp.text_field :content %>
        <%= hidden_field_tag :book_id, base_period.book.id %>
      <% end %>
    <% end %>
    <%= f.submit '次へ' %>
    <!-- @book#showにリンク(books_controllerで指定) -->
  <% end %>
  <%= link_to 'トップに戻る', root_path %>
</div>

app/views/base_periods/new_names.html.erb
<!-- base_periods#new_name -->

<div class="container contents-wrapper">
  <h2>誕生から今までを大まかな時期に分けてみよう</h2>


<!-- base_periodsの新規登録(books#updateに回す)-->
  <%= form_for(@book, url: book_path(@book , xxx: "yyy"), html: {method: "patch"}) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

    <%= f.fields_for :base_periods, @base_periods do |bp| %>
      <%= bp.label :name, 'Period' %>
      <%= bp.text_field :name %>
      <%= hidden_field_tag :book_id, @base_period.book.id %>
    <% end %>

    <%= f.submit '次へ' %>
    <!-- @book#showにリンク(books_controllerで指定) -->
  <% end %>

  <%= link_to 'トップに戻る', root_path %>
  </div>

app/views/base_periods/show.html.erb
<!-- base_periods#show-->

<div class="container contents-wrapper">
  <h2>base_periods#show</h2>
  <p><%= @base_period.name %> &gt; <%= @base_period.content %></p>
</div>