config/routes.rb
Rails.application.routes.draw do

  #ログイン
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  #トップページ
  root to: 'toppages#index'
  
  #アカウント作成・編集・削除
  get 'signup', to: 'users#new'
  resources :users do
    collection do
      get :search
    end
  end
  
  #Book作成
  resources :books

  
  #WholeAnswer作成
  resources :whole_answers
  
  #base_periods作成
  resources :base_periods, :except => [:new] do
    collection do
      get :new_names
      get :new_contents
      post :create_names
      post :create_contents
    end
    member do
      get :new_content
    end
  end
end

app/views/layouts/_error_messages.html.erb
<div class="container contents-wrapper">
  <% if model.errors.any? %>
    <div class="alert alert-warning">
      <ul>
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="container contents-wrapper">  
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top headroom" >
	<div class="container">
		<div class="navbar-header">
			<!-- Button for smallest screens -->
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
			<a class="navbar-brand" href="/"><img src="assets/images/logo.png" alt="人となりBook"></a>
		</div>
	<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav pull-right">
        <% if logged_in? %>
          <li><%= link_to 'マイページ', user_path(current_user)  %></li>
          <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'アカウント登録', signup_path %></li>
          <li><%= link_to 'ログイン', login_path %></li>
        <% end %>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</div> 
<!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>

	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Sergey Pozhilov (GetTemplate.com)">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
	<title>人となりBook</title>
	<%= csrf_meta_tag %>

	<link rel="shortcut icon" href="../../assets/images/gt_favicon.png">
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
	
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="/CSS/bootstrap.min.css">
	<link rel="stylesheet" href="/CSS/font-awesome.min.css">

	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="/CSS/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="/CSS/main.css">

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src=/js/html5shiv.js"></script>
	<script src="/js/respond.min.js"></script>
	<![endif]-->
	

	
	
</head>

<body class="home">
	
<%= render 'layouts/navbar' %>
<%= render 'layouts/flash_messages' %>
  
    <%= yield %>
	


	<footer id="footer" class="top-space">

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<%= link_to 'Top', root_path %>| 
								<%= link_to 'アカウント作成', signup_path %>| 
								<%= link_to 'ログイン', login_path %>| 
								<%= link_to 'Contact', root_path %>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2019, Chika Ono. Designed by <a href="http://gettemplate.com/" rel="designer">gettemplate</a> 
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

	</footer>	
		




	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="/js/headroom.min.js"></script>
	<script src="/js/jQuery.headroom.min.js"></script>
	<script src="/js/template.js"></script>
	
	
	<!-- bookblock用読み込み追加分ここから -->
    
  <link rel="stylesheet" type="text/css" href="/CSS/bookblock.css" />
  <link rel="stylesheet" type="text/css" href="/CSS/demo1.css" />
  
  <script src="/js/modernizr.custom.js"></script>
  <script src="/js/jquerypp.custom.js"></script>
  <script src="/js/jquery.bookblock.js"></script>
    
	<script type="text/javascript">
    	var Page = (function () {
     
    		var config = {
    				$bookBlock: $('#bb-bookblock'),
    				$navNext: $('#bb-nav-next'),
    				$navPrev: $('#bb-nav-prev'),
    				$navFirst: $('#bb-nav-first'),
    				$navLast: $('#bb-nav-last')
    			},
    			init = function () {
    				config.$bookBlock.bookblock({
    					speed: 1000,
    					shadowSides: 0.8,
    					shadowFlip: 0.7,
    					direction : 'ltr',
    					orientation : 'vertical' 
    				});
    				initEvents();
    			},
    			initEvents = function () {
     
    				var $slides = config.$bookBlock.children();
     
    				
    				config.$navNext.on('click touchstart', function () {
    					config.$bookBlock.bookblock('next');
    					return false;
    				});
     
    				config.$navPrev.on('click touchstart', function () {
    					config.$bookBlock.bookblock('prev');
    					return false;
    				});
     
    				config.$navFirst.on('click touchstart', function () {
    					config.$bookBlock.bookblock('first');
    					return false;
    				});
     
    				config.$navLast.on('click touchstart', function () {
    					config.$bookBlock.bookblock('last');
    					return false;
    				});
     
    				
    				$slides.on({
    					'swipeleft': function (event) {
    						config.$bookBlock.bookblock('next');
    						return false;
    					},
    					'swiperight': function (event) {
    						config.$bookBlock.bookblock('prev');
    						return false;
    					}
    				});
     
    				
    				$(document).keydown(function (e) {
    					var keyCode = e.keyCode || e.which,
    						arrow = {
    							left: 37,
    							up: 38,
    							right: 39,
    							down: 40
    						};
     
    					switch (keyCode) {
    					case arrow.left:
    						config.$bookBlock.bookblock('prev');
    						break;
    					case arrow.right:
    						config.$bookBlock.bookblock('next');
    						break;
    					}
    				});
    			};
     
    		return {
    			init: init
    		};
     
    	})();
    </script>
    <script>
    	Page.init();
    </script>
    	
<!-- bookblock用読み込み追加分ここまで -->
	
</body>
</html>